version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rainsafe_ai
    ports:
      - "8000:8000"
      - "5500:5500"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
